version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: movie_data_user
      POSTGRES_PASSWORD: Viccid001
      POSTGRES_DB: movie_data_db
    ports:
      - "5434:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./data:/data
      - ./infra_setup/init.sql:/docker-entrypoint-initdb.d/init.sql
