version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: netflix_data_user
      POSTGRES_PASSWORD: Viccid11001
      POSTGRES_DB: netflix_data_db
    ports:
      - "5434:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./data:/data
      - ./infra_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
